version: '3'

services:
  react:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
       - /app/react/node_modules
       - .:/app/react
    
